<h2>Description</h2>

<section>
    <h3>Présentation</h3>

    <img src="../assets/img/27980479939_0fbc0c80e4_b.jpg" alt="deus ex">
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda debitis adipisci earum laborum neque vel commodi rem hic quis autem!</p>
    <img src="../assets/img/wp7769083.jpg" alt="message d'erreur windows">
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iusto reprehenderit esse sequi molestiae est eius officia dolores voluptates, maiores voluptatem.</p>
    <img src="../assets/img/x1sr1lob3ai41.jpg" alt="">
</section>